appName = "Fiber APP Template"
timezone = "Asia/Shanghai"
languages = ["zh", "en"]
goroutines = 50

[server]
address = "0.0.0.0"
port = "8888"
secret = "FiberTemplate"

[db]
type = "sqlite"
dsn = "app.db"
enableMigrate = true

[redis]
enable = false
dsn = "rediss://:@localhost:6379"
expire = 3600

[scheduler]
enableTasks = [""]
runAtStartupTasks = ["ExampleTask"]

[proxy]
baseUrl = "https://example.com"
secret = "FiberTemplate"

[logger]
level = 0
stackTraceLevel = 2
filename = "logs/app.log"
maxSize = 100
maxBackups = 30
maxAge = 30
enableCompress = true